"""initial

Revision ID: bfa568f84d6f
Revises: 
Create Date: 2026-05-12 01:22:28.184387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa568f84d6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disease_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=True),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('disease_name', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('prevention_tips', sa.JSON(), nullable=True),
    sa.Column('analysis_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irrigation_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('land_size_acres', sa.Float(), nullable=False),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.Column('daily_litres', sa.Float(), nullable=True),
    sa.Column('weekly_litres', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('schedule_json', sa.JSON(), nullable=True),
    sa.Column('tips', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('forecast_days', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('recommendation_action', sa.String(length=20), nullable=True),
    sa.Column('predictions_json', sa.JSON(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profit_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('land_size_acres', sa.Float(), nullable=False),
    sa.Column('irrigation', sa.Boolean(), nullable=True),
    sa.Column('cost_total', sa.Float(), nullable=True),
    sa.Column('cost_per_acre', sa.Float(), nullable=True),
    sa.Column('cost_breakdown_json', sa.JSON(), nullable=True),
    sa.Column('profit_conservative', sa.Float(), nullable=True),
    sa.Column('profit_moderate', sa.Float(), nullable=True),
    sa.Column('profit_optimistic', sa.Float(), nullable=True),
    sa.Column('roi_conservative', sa.Float(), nullable=True),
    sa.Column('roi_moderate', sa.Float(), nullable=True),
    sa.Column('roi_optimistic', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('breakdown_json', sa.JSON(), nullable=True),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.Column('mitigations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yield_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('land_size_acres', sa.Float(), nullable=False),
    sa.Column('soil_type', sa.String(length=50), nullable=True),
    sa.Column('irrigation', sa.Boolean(), nullable=True),
    sa.Column('estimate_conservative', sa.Float(), nullable=True),
    sa.Column('estimate_moderate', sa.Float(), nullable=True),
    sa.Column('estimate_optimistic', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('multipliers_json', sa.JSON(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('market_queries')
    op.drop_table('crop_recommendations')
    op.drop_table('conversations')
    op.drop_table('disease_detections')
    op.drop_table('event_logs')
    op.add_column('farmers', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('farmers', sa.Column('land_size_acres', sa.Float(), nullable=True))
    op.add_column('farmers', sa.Column('budget_inr', sa.Float(), nullable=True))
    op.add_column('farmers', sa.Column('crops', sa.JSON(), nullable=True))
    op.add_column('farmers', sa.Column('irrigation_type', sa.String(length=50), nullable=True))
    op.add_column('farmers', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('farmers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('farmers', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('farmers', 'soil_type',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('farmers', 'location',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_unique_constraint(None, 'farmers', ['user_id'])
    op.create_foreign_key(None, 'farmers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('farmers', 'name')
    op.drop_column('farmers', 'budget')
    op.drop_column('farmers', 'language')
    op.drop_column('farmers', 'land_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('land_size', sa.FLOAT(), nullable=True))
    op.add_column('farmers', sa.Column('language', sa.VARCHAR(length=30), nullable=True))
    op.add_column('farmers', sa.Column('budget', sa.FLOAT(), nullable=True))
    op.add_column('farmers', sa.Column('name', sa.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'farmers', type_='foreignkey')
    op.drop_constraint(None, 'farmers', type_='unique')
    op.alter_column('farmers', 'location',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('farmers', 'soil_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    op.alter_column('farmers', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('farmers', 'updated_at')
    op.drop_column('farmers', 'experience_years')
    op.drop_column('farmers', 'irrigation_type')
    op.drop_column('farmers', 'crops')
    op.drop_column('farmers', 'budget_inr')
    op.drop_column('farmers', 'land_size_acres')
    op.drop_column('farmers', 'user_id')
    op.create_table('event_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=80), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disease_detections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('farmer_id', sa.INTEGER(), nullable=True),
    sa.Column('crop_type', sa.VARCHAR(length=40), nullable=True),
    sa.Column('disease', sa.VARCHAR(length=120), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=60), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('farmer_id', sa.INTEGER(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('intent', sa.VARCHAR(length=40), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_recommendations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('farmer_id', sa.INTEGER(), nullable=True),
    sa.Column('recommended_crops', sa.TEXT(), nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_queries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('farmer_id', sa.INTEGER(), nullable=True),
    sa.Column('crop', sa.VARCHAR(length=40), nullable=True),
    sa.Column('current_price', sa.FLOAT(), nullable=True),
    sa.Column('trend', sa.VARCHAR(length=30), nullable=True),
    sa.Column('recommendation', sa.VARCHAR(length=30), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('yield_predictions')
    op.drop_table('risk_assessments')
    op.drop_table('profit_analyses')
    op.drop_table('market_predictions')
    op.drop_table('irrigation_plans')
    op.drop_table('disease_reports')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
